### ISSUE TITLE
OSError: [Errno 5] Input/output error <<-- Why am I getting this error

### ISSUE THREAD

**Issue by Choikyungho9** [makerportal/tfluna-python#1]
pi@raspberrypi:~/tfluna $ sudo python3 tfluna_realtime.py
Set Baud Rate = 115200
Version - TF-Luna.     STD.03.00.09
Starting Ranging...
Traceback (most recent call last):
  File "tfluna_realtime.py", line 184, in <module>
    distance,strength,temperature = read_tfluna_data() # read values
  File "tfluna_realtime.py", line 22, in read_tfluna_data
    counter = ser.in_waiting # count the number of bytes waiting to be read
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 467, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
OSError: [Errno 5] Input/output error

**OSError: [Errno 5] Input/output error** <<-- Why am I getting this error?

I can't get any data even if I run the sensor because of this error.

Please help me

**Comment by josh-hrisko** [comment]
Are you using a Raspberry Pi? If so, have you enabled the serial port? Our tutorial can be used as a reference for getting started: https://makersportal.com/blog/distance-detection-with-the-tf-luna-lidar-and-raspberry-pi

**Comment by PjotrG** [comment]
tfluna_realtime sometime ran fine, now 
I'm getting the same error as above, though tfluna_test stll runs fine.
Also getting sometimes with tfluna_realtime.py:
Traceback (most recent call last):
  File "tfluna_realtime.py", line 118, in <module>
    set_samp_rate(100) # set sample rate 1-250
  File "tfluna_realtime.py", line 40, in set_samp_rate
    ser.write(samp_rate_packet) # send sample rate instruction
AttributeError: 'NoneType' object has no attribute 'write'
Can anybody help??

**Comment by josh-hrisko** [comment]
It looks like the serial isn't starting, which is why it has the 'NoneType' attribute error. What are the specifications on your Raspberry Pi? There could be a timing issue, which may be resolved by placing a time.sleep(0.1) between certain serial processes.

**Comment by PjotrG** [comment]
Thanx Josh, so far no success.
Introduced several time.sleep(0.1), however looses "ser" 
during set_baudrate ???
Hardware details:
Rpi3B+ (oper. headless via VNC)
sensor: Lidar TF mini (no Luna ??) connected to GPIO
(changed power supply from external to GPIO, tfluna_test.py now more stable!!)
does this makes sense?

**Comment by josh-hrisko** [comment]
PjotrG,

This code is for the TF-Luna, I haven't tested with the TF-Mini. I'm not sure if the serial returns are the same, this could be the issue. You may want to check the datasheet for the TF-Mini and verify this. That could be your issue. You could also just comment out the set_baudrate command.

**Comment by PjotrG** [comment]
Thanx Josh, this works at least, will check later whether I can fix the rest.
@Choikyungho9 : in my case it was a power isuue, you might check your power supply

**Comment by Choikyungho9** [comment]
@PjotrG I tried changing the power supply according to your advice. Then, the sensor input was received better than before. Thank you so much for your advice.

**Comment by PjotrG** [comment]
@Choikyungho9 and all Pi3 users this might be useful:
to run the TF-mini stable you have to switch the UARTs either by diabling the
serial console in the configuration menu
![grafik](https://user-images.githubusercontent.com/57295038/109933566-d9d8c700-7ccb-11eb-8c6f-a09f603b4402.png)
or by laying bluetooth on the miniUART:
add the line: dtoverlay=pi3-miniuart-bt
 to /boot/cmdline.txt
An external 5V power supply is apparently also useful.
With all this it worked fine in my case.

**Comment by josh-hrisko** [comment]
@PjotrG and @Choikyungho9 Thank you both for figuring this out with the TF-Mini. I should perhaps add another section on interfacing with the TF-Mini.
